defmodule StreamflixWebWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :streamflix_web

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_streamflix_web_key",
    signing_salt: "Ig7MA6EW",
    encryption_salt: "rK3vPx9Q",
    same_site: "Lax",
    http_only: true,
    secure: true,
    # 30 days in seconds (for remember me)
    max_age: 2_592_000
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  socket "/ws", StreamflixWebWeb.UserSocket, websocket: [timeout: 120_000]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: {:streamflix_web, "priv/static"},
    gzip: not code_reloading?,
    brotli: not code_reloading?,
    only: StreamflixWebWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug StreamflixWebWeb.Plugs.LoggerMetadata
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    length: 256_000

  # 256 KB max body (spec §11); for larger uploads use multipart
  plug StreamflixWebWeb.Plugs.SecurityHeaders

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug StreamflixWebWeb.Plugs.CORS
  plug StreamflixWebWeb.Plugs.Compress
  plug StreamflixWebWeb.Router
end
